import assert from 'node:assert/strict';
import {chromium} from 'playwright-core';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
try {
 const page=await browser.newPage({viewport:{width:1600,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.READER_URL || 'http://127.0.0.1:8767/');
 await page.locator('.book-card').first().waitFor();
 await page.waitForFunction(()=>!document.querySelector('.continue-stats')?.textContent.includes('正在'));
 const row=page.locator('.book-card').first();
 const title=await row.locator('.book-card-title').textContent();
 assert.equal(await row.locator('.book-card-meta').count(),1);
 assert.equal(await row.locator('.book-open').textContent(),'打开 →');
 await page.mouse.move(0,0);
 await page.screenshot({path:'test-results/library-row-default.png'});
 const box=await row.boundingBox();await page.mouse.move(box.x+200,box.y+30);
 await page.waitForTimeout(150);
 assert.deepEqual(await row.boundingBox(),box);
 await page.screenshot({path:'test-results/library-row-hover.png'});
 await page.mouse.click(box.x+200,box.y+30);
 await page.locator('#book-overview').waitFor({state:'visible'});
 assert.equal(await page.locator('.overview-book-heading h1').textContent(),title);
 await page.locator('.overview-back').click();
 await page.waitForFunction(()=>!document.querySelector('#library-home').hidden && !document.querySelector('.continue-stats')?.textContent.includes('正在'));
 await page.waitForTimeout(180);
 await row.locator('summary').click();await page.waitForTimeout(150);
 await page.screenshot({path:'test-results/library-row-menu.png'});
 assert.equal(await page.locator('#book-overview').isVisible(),false);
 await row.getByRole('button',{name:'查看全书结构',exact:true}).click();
 await page.locator('#book-overview').waitFor({state:'visible'});
 assert.equal(await page.locator('.overview-book-heading h1').textContent(),title);
 await page.locator('.overview-back').click();
 await page.waitForFunction(()=>!document.querySelector('#library-home').hidden && !document.querySelector('.continue-stats')?.textContent.includes('正在'));
 await page.waitForTimeout(180);
 await page.mouse.move(0,0);
 await row.locator('summary').focus();await page.keyboard.press('Shift+Tab');
 assert.equal(await row.locator('.book-open').evaluate(e=>e===document.activeElement),true);
 await page.waitForTimeout(150);
 await page.screenshot({path:'test-results/library-row-focus.png'});
 assert.deepEqual(await row.boundingBox(),box);
 assert.equal(await row.evaluate(e=>getComputedStyle(e).outlineStyle),'solid');
 await page.keyboard.press('Enter');await page.locator('#book-overview').waitFor({state:'visible'});
 await page.locator('.overview-back').click();
 await page.waitForFunction(()=>!document.querySelector('#library-home').hidden && !document.querySelector('.continue-stats')?.textContent.includes('正在'));
 await page.waitForTimeout(180);
 await row.locator('summary').focus();await page.keyboard.press('Enter');
 assert.equal(await row.locator('details').getAttribute('open'),'');
 const chooserPromise=page.waitForEvent('filechooser');
 await row.getByRole('button',{name:'添加新版本',exact:true}).click();
 const chooser=await chooserPromise;
 assert.equal(await chooser.element().getAttribute('accept'),'application/pdf,.pdf');
 await chooser.setFiles([]);
 let deletePrompt='';
 page.once('dialog',async dialog=>{deletePrompt=dialog.message();await dialog.dismiss();});
 await row.getByRole('button',{name:'删除教材',exact:true}).click();
 assert.ok(deletePrompt.includes(title));
 assert.equal(await row.locator('.book-card-title').textContent(),title);
 await page.keyboard.press('Escape');assert.equal(await row.locator('details').getAttribute('open'),null);
 await row.locator('.book-open').click();
 await page.locator('#book-overview').waitFor({state:'visible'});
 await page.locator('.overview-back').click();
 await page.waitForFunction(()=>!document.querySelector('#library-home').hidden && !document.querySelector('.continue-stats')?.textContent.includes('正在'));
 await page.waitForTimeout(180);
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.waitForFunction(()=>getComputedStyle(document.querySelector('.book-card')).transitionDuration==='0s');
 assert.equal(await row.evaluate(e=>getComputedStyle(e).transitionDuration),'0s');
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({status:'PASS',title,rowClick:true,explicitOpen:true,menuOverview:true,addVersionChooser:true,deleteConfirmCanceled:true,layoutStable:true,keyboard:true,reducedMotion:true}));
} finally {await browser.close();}
